spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/security_studies
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000 # 1 hour in miliseconds
      refresh-token-expiration: 604800000 # 7 days in miliseconds
server:
  port: 8080
  servlet:
    context-path: /api
---

spring:
  config:
    activate:
      on-profile: dev
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/security_studies_dev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
security:
  jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000 # 1 hour in miliseconds
      refresh-token-expiration: 604800000 # 7 days in miliseconds

server:
  port: 8081
  servlet:
    context-path: /api
